export const initialState = {
  posts: [],
  selectedPostData: {
    createdAt: '',
    changedAt: '',
    id: '',
    changedByAuthorId: '',
    changedByAuthorName: '',
    changedByAuthorType: '',
    authorId: '',
    authorName: '',
    authorType: '',
    sku: '',
    name: '',
    brand: '',
    brandId: '',
    sectionId: '',
    section: '',
    parentCategoryId: '',
    parentCategory: '',
    categoryId: '',
    category: '',
    availability: '', // * notAvailable, awaitingInStock, onStock, toOrder, individualOrder,
    notAvailable: true,
    toOrder: false,
    awaitingTime: '',
    individualOrder: false,
    productingTime: '',
    description: '',
    innerComment: '',
    isApproved: false,
    isVisible: false,
    cost: 0,
    isCommission: false,
    commission: 0,
    currency: '',
    price: 0,
    sale: 0,
    cashbackId: 0,
    sizesTable: '',
  },
  selectedPostId: '',
  markedPosts: [],
  searchQuery: '',
  searchParam: '',
  isLoading: false,
  error: null,
};
