export const actionsBlockLarge = [
  { name: 'search', title: 'Пошук', iconId: 'search', status: true },
  { name: 'filter', title: 'Фільтр', iconId: 'filter-off', status: true },
  { name: 'link', title: 'Посилання', iconId: 'link', status: false },
  { name: 'copy', title: 'Копіювати', iconId: 'copy', status: true },
  { name: 'share', title: 'Поділитись', iconId: 'share', status: true },
  { name: 'refresh', title: 'Оновити', iconId: 'refresh', status: true },
  { name: 'edit', title: 'Редагувати', iconId: 'edit', status: true },
  { name: 'delete', title: 'Видалити', iconId: 'delete', status: true },
  { name: 'create', title: 'Створити', iconId: 'plus', status: true },
  { name: 'print', title: 'Друк', iconId: 'print', status: false },
  { name: 'export', title: 'Експорт', iconId: 'upload', status: true },
  { name: 'import', title: 'Імпорт', iconId: 'download', status: true },
];
export const actionsBlockSmall = [
  { name: 'link', title: 'Посилання', iconId: 'link', status: true },
  { name: 'copy', title: 'Копіювати', iconId: 'copy', status: true },
  { name: 'share', title: 'Поділитись', iconId: 'share', status: true },
  { name: 'refresh', title: 'Оновити', iconId: 'refresh', status: true },
  { name: 'edit', title: 'Редагувати', iconId: 'edit', status: true },
  { name: 'delete', title: 'Видалити', iconId: 'delete', status: true },
  { name: 'create', title: 'Створити', iconId: 'plus', status: true },
  { name: 'print', title: 'Друк', iconId: 'print', status: false },
  { name: 'export', title: 'Експорт', iconId: 'upload', status: true },
  { name: 'import', title: 'Імпорт', iconId: 'download', status: true },
];
