export const categoriesArr = [
  {
    sectionId: '001',
    section: 'Чоловікам',
    categories: [
      {
        sectionId: '001',
        section: 'Чоловікам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '001-001',
        category: 'Взуття',
        categories: [
          {
            sectionId: '001',
            section: 'Чоловікам',
            parentCategoryId: '001-001',
            parentCategory: 'Взуття',
            categoryId: '001-001-001',
            category: 'Взуття класичне',
            categories: [
              {
                sectionId: '001',
                section: 'Чоловікам',
                parentCategoryId: '001-001-001',
                parentCategory: 'Взуття класичне',
                categoryId: '001-001-001--001',
                category: 'Дербі',
                categories: [],
              },
              {
                sectionId: '001',
                section: 'Чоловікам',
                parentCategoryId: '001-001-001',
                parentCategory: 'Взуття класичне',
                categoryId: '001-001-001-002',
                category: 'Броги',
                categories: [],
              },
            ],
          },
          {
            sectionId: '001',
            section: 'Чоловікам',
            parentCategoryId: '001-001',
            parentCategory: '',
            categoryId: '001-001-002',
            category: 'Взуття спортивне',
            categories: [],
          },
        ],
      },
      {
        sectionId: '001',
        section: 'Чоловікам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '001-002',
        category: 'Верхній одяг',
        categories: [],
      },
      {
        sectionId: '001',
        section: 'Чоловікам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '001-003',
        category: '',
        categories: [],
      },
      {
        sectionId: '001',
        section: 'Чоловікам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '001-004',
        category: '',
        categories: [],
      },
    ],
  },
  {
    sectionId: '002',
    section: 'Жінкам',

    categories: [
      {
        sectionId: '002',
        section: 'Жінкам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '',
        category: '',
        categories: [],
      },
      {
        sectionId: '002',
        section: 'Жінкам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '',
        category: '',
        categories: [],
      },
      {
        sectionId: '002',
        section: 'Жінкам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '',
        category: '',
        categories: [],
      },
      {
        sectionId: '002',
        section: 'Жінкам',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '',
        category: '',
        categories: [],
      },
    ],
  },
  {
    sectionId: '003',
    section: 'Дітям',
    categories: [
      {
        sectionId: '003',
        section: 'Дітям',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '',
        category: 'Верхній одяг',
        categories: [],
      },
      {
        sectionId: '003',
        section: 'Дітям',
        parentCategoryId: '',
        parentCategory: '',
        categoryId: '',
        category: 'Взуття',
        categories: [],
      },
      {
        sectionId: '003',
        section: 'Дітям',
        parentCategoryId: '',
        categoryId: '',
        category: 'Костюми',
        categories: [],
      },
      {
        sectionId: '003',
        section: 'Дітям',
        parentCategory: '',
        categoryId: '',
        category: 'Футболки, сорочки',
        categories: [],
      },
    ],
  },
];
